### ISSUE TITLE
Question to vit9696: Tips for prevgenting graphics flickering

### ISSUE THREAD

**Issue by JurekR** [lvs1974/NvidiaGraphicsFixup#15] opened 2018-04-16 09:17 UTC
Hi vit,

I would like to ask you a couple of questions, because I think you are the person with the most overall knowledge regarding the nvidia driver on macos outside from nvidia (which is not very helpful).

I use a 1050gt nvidia on a haswell rig using kernel XCPM, imac14,2. It worked without graphics errors on 10.12.6 with f07 driver. The performance now is much better with 10.13.4 and your lag fix than it was on 10.12.6. The only problem remaining is the graphics corruption that appears. So far I observed the following:

- It happens while specific applications are open, for example Mail, or Safari, but only with some specific webpages, not all. So I guess in the moment when specific extra functionality is used

- I looks like lines are not drawn correctly anymore, the lines are spread then over the desktop, and some areas are not redrawn anymore. If you then resize the windows, or close e.g. Mail, it will turn back to normal

- I now tried various versions of older drivers, patched for 10.13.4: 
30.103 (best performance), 25.160, 25.106, 25.104 and 25.102. All will show this graphics errors, I would even say the recent driver is the most usable.

- People with other card models but same chipset generation seem not to have these problems, e.g. 1070 users.

My questions would be:

- What do you think is the cause for these errors?

- Do you know a way to fix it? Should I disable Metal like you described?

- It seems to happen only on hacks, not on real macs?

- Could it be related to pc style graphics card power management?

- Could this be related to Kernel XCPM or the smbios model?

Thanks for giving some insight infos!

**Comment by cristianraiber** [comment] 2018-04-16 09:52
Actually, 1070 users are also having this issue as well :) 

I'm one of them.

**Comment by lemjello** [comment] 2018-04-16 15:03
I have a 1080ti and am having the same issues. 10.13.4 and latest web driver. Rolling back to the previous nvidiagraphicsfixup 1.2.5 has helped. In fact, most of the corruption issues you described is gone with the latest web driver and 1.2.5. All the issues you describe above came back, although less than before the 1.2.5 NGF, with using the 1.2.6 release.  Super helpful project all around though. Without this, I don't think my 1080ti would even be usable!

**Comment by vit9696** [comment] 2018-04-16 18:06
Hello,

First of all, let me state, that despite your impression I am fully aware of the visual corruption issues present in the driver. However, in two-week time I managed to reproduce them only once with the official drivers on NVIDIA Kepler. From what I can tell, unlike the official drivers, where the glitches are extremely rare, web drivers are far more prone to these bugs. Since it appears that Apple backports web driver changes on case by case basis, it is unlikely that the issue is specific to hacks, just for the time being it is much rarer on the latter.

NVIDIA visual issues are not new. They partially existed in all the previous releases of 10.13, at least the black rectangles, and in 10.12 there were small icon and image corruptions due to locale issues affecting the metal shader compiler. The rest may be new, but I would rather not theorise.

While it may not be well-known, but the last published release notes for 10.13.4 contained a radar reference for a screen corruption on certain devices in the list of the known issues. It is unclear whether it got fixed in the release, and what actual devices were affected. For example, Intel Coffee Lake GPUs still have various issues as well. Even if the issue was fixed, 10.13.4 brought heavy changes to the whole graphical stack… so you better brace yourself and hope for the best.

It appears that the visual artifacts indeed started to happen more frequently both after 10.13.4 and the performance workaround in NvidiaGraphicsFixup. I cannot speculate about the cause, because what NvidiaGraphicsFixup implements is pretty much the original Apple/NVIDIA code found in 10.13.0 drivers and earlier. Without an in-depth research, which would require an unreasonably large amount of time, it is simply impossible to do any better. By now Apple should have received all the technical details about the bug, but just like everybody else I do not know how much priority this is given to.

From the top of my head I could suggest several measures which may (or may not) help:
1. Always use the latest version of macOS, NvidiaGraphicsFixup and web drivers if you cannot stay on official drivers. New NvidiaGraphicsFixup  versions should behave all the same or better except with random memory corruptions if any.
2. Clear the caches or reinstall the operating system. Metal compiler generates shader caches for all the applications you launch. These shaders are stored on the disk, and if they happen to contain any issues, they may not be regenerated. You may try the commands below at your own risk. Reboot immediately afterwards.
```
sudo find /private -name com.apple.metal -exec rm -rf {} \;
sudo rm -rf /Library/Caches/*
sudo rm -rf ~/Library/Caches/*
```
3. There exists a completely unrelated memory corruption in NVIDIA Web driver specific to Pascals. Due to the nature of the bug the trigger sequence is the matter of luck or rather RAM usage. There is no clear evidence what is the best way to workaround it (because the bug will remain there no matter what), but deleting the CUDA driver, using `ngfxcompat=0`, or cleaning the caches may be of some help. More details here: https://github.com/lvs1974/NvidiaGraphicsFixup/commit/4301f3668ee814bafd7d75be020ce5cb9b397f95.

4. You could try to disable Metal entirely just as explained in the changelog. It is known to reduce VRAM usage and may help with the glitches as well.

5. As a last resort you could add `ngfxsubmit=0` and get less glitches at a cost of severe lags. Note, that the glitches seem not to affect the operating system itself, and disappear quickly after they show up. So perhaps it is reasonable to just wait for an os update.

I will leave the issue open for a few days to avoid duplicate spam, but I request you not to post anything unless you have some new _technical_ information. Reading all the comments, which are close to being the same takes a lot of time, and I am not here to provide support, that's what Apple Radar bugtracker and support.apple.com are for.

**Comment by ReddestDream** [comment] 2018-04-17 20:41
New Nvidia driver 387.10.10.10.30.106 out today for 10.13.3 seems to have fixed the visual artifacts I had noticed in Chrome/Chromium/Electron-based apps. :)

**Comment by jaux** [comment] 2018-04-18 05:10
I'm using 1060, 30.103 + NGF 1.2.5 had worked well for me until I upgraded to NGF 1.2.6. I have just upgraded to to 30.106, I'll report my experience back later.

**Comment by JurekR** [comment] 2018-04-18 08:51
Yes, 30.106 seems to fixed the corruption issues here, too!! Did nvidia actually start to listen to bug reports?

**Comment by star-affinity** [comment] 2018-04-18 11:31
@JurekR Before 387.10.10.10.30.106 I was able to do this: https://www.dropbox.com/s/6quz7s6chfwb1jc/Colour_glitches.m4v?dl=0

Reported to Nvidia and they were able to reproduce and fix. Sounds like it could be related to the other visual glitches people has been seeing. So they (Nvidia) definitely listens to reports. :)

**Closed** 2018-04-18 11:34 UTC
