### ISSUE TITLE
Switchable graphics on MacBook Pro not working with this kext

### ISSUE THREAD

**Issue by kecinzer** [lvs1974/NvidiaGraphicsFixup#13] opened 2018-04-12 17:49 UTC
I applied this kext on my MacBook Pro 15" 2014 and it fixes slow GeForce graphics performance for me. That is great. But this kext also breaks integrated Intel GPU.
It is possible to make it work and also allow switching to Intel GPU?
Thanks.

**Comment by vit9696** [comment] 2018-04-12 18:01
Hi,
Adding `ngfxpatch=none` to `boot-args` should fix your issue. I.e. executing the following in Terminal:
```
sudo nvram boot-args="ngfxpatch=none"
```
If this works, I could make some changes to disable the patches for certain macmodels (i.e. `iMac13,2`, `iMac14,2`, `MacBookPro11,3` — yours is this one, right?) out of the box, so that the manual change is not required.

Also, would you please file [a bugreport](https://developer.apple.com/bug-reporting/) at Apple, because the issue does not reproduce on all GPU models, and while it is a very serious failure, making Apple notice it is not an easy task without the actual mac specs.

**Comment by kecinzer** [comment] 2018-04-13 04:27
Hello,
thank you so much, this boot arguments fixes it for me!
I have MacBookPro11,3 you can disable it for this model I think.

I opened few bugreports to Apple already, but without success. They always claimed that its fixed. I was also in Apple Store with my MacBook, but Apple employee almost laught to me.

This GeForce slow performance bug is there from the first version of High Sierra and still not be fixed by Apple. You can look at this topics for more information - https://discussions.apple.com/message/33279686 and https://forums.macrumors.com/threads/any-news-about-the-macbook-pro-nvidia-gpu-lag-yet.2088300/
Many other people started bugreport as well.

Only your kext allows me to use High Sierra on my MacBook.
Thank you! Great work.

**Comment by vit9696** [comment] 2018-04-13 05:04
Good morning,

Thank you for the confirmation, I committed my yesterday changes upstream. Here is the prerelease kext version to try: [1.2.6-prerelease-4301f36.zip](https://github.com/lvs1974/NvidiaGraphicsFixup/files/1905853/1.2.6-prerelease-4301f36.zip). Please confirm that it works for you without the boot arguments.

Regarding the links you posted, they are good to get an idea of what the bug looks like. However, Apple employees do not read the forum discussions, and it would help a lot if you post the radar IDs (Apple bugtracker IDs) you created here. Thanks.

The performance bug actually did not exist in early 10.13.0 versions, and that's what allowed me to track it down.

**Comment by ReddestDream** [comment] 2018-04-13 05:56
I did not have any iGPU brokenness with previous releases on my 2012 rMBP (MacbookPro10,1), and it's all still good after this last commit.

**Comment by kecinzer** [comment] 2018-04-13 06:10
Morning,
I can confirm that latest version 1.2.6 switches GPUs without boot args. Thanks!
I just mentioned, that GeForce performance is much more better with KEXT but still is not that fast like with Intel GPU. I don't know what Apple did wrong 😞.

I created another bug report with ID 39404756. The older close one has ID 36191341.

**Comment by ReddestDream** [comment] 2018-04-13 06:17
@kecinzer Thanks for creating a bug report. Apple needs to know how bad this is . . .

**Comment by vit9696** [comment] 2018-04-13 07:43
Thanks for the IDs. I uploaded the 1.2.6 [release binaries](https://github.com/lvs1974/NvidiaGraphicsFixup/releases) for the time being. Closing the issue as resolved.

**Closed by vit9696** 2018-04-13 07:43 UTC
